/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.registration;

import model.main.MainJFrame;

/**
 *
 * @author Dell
 */
public class RegistrationSideJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationSideJPanel
     */
    javax.swing.JSplitPane splitPane;
    public RegistrationSideJPanel(javax.swing.JSplitPane splitPane) {
        initComponents();
        this.splitPane = splitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgfactory = new javax.swing.JLabel();
        lblRoleHeading = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        lblBack = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        imgingsupplier = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblIngredient = new javax.swing.JLabel();
        btnIngSupplier = new javax.swing.JButton();
        imgManufacturer = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        btnManufacturer = new javax.swing.JButton();
        imgFDA = new javax.swing.JLabel();
        lblANSI = new javax.swing.JLabel();
        btnANSI = new javax.swing.JButton();
        imgDistributor = new javax.swing.JLabel();
        lblDistributor = new javax.swing.JLabel();
        btnDistributor = new javax.swing.JButton();
        imgMaterialDepot = new javax.swing.JLabel();
        lblMaterialDepot = new javax.swing.JLabel();
        btnMaterialDepot = new javax.swing.JButton();
        imgContractor = new javax.swing.JLabel();
        lblContractor = new javax.swing.JLabel();
        btnContractor = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgfactory.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgfactory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgfactory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Account.png"))); // NOI18N
        add(imgfactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 60));

        lblRoleHeading.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        lblRoleHeading.setForeground(new java.awt.Color(102, 102, 102));
        lblRoleHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoleHeading.setText("Choose Role");
        add(lblRoleHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, 50));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, -1, 90));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70, -1));

        lblBack.setBackground(new java.awt.Color(153, 153, 153));
        lblBack.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Double Left.png"))); // NOI18N
        lblBack.setText("BACK");
        add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 70, 30));

        imgingsupplier.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgingsupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgingsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Lab Items.png"))); // NOI18N
        add(imgingsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 60));

        lblSupplier.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSupplier.setText("Supplier");
        add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        lblIngredient.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblIngredient.setForeground(new java.awt.Color(255, 255, 255));
        lblIngredient.setText("Ingredient");
        add(lblIngredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnIngSupplier.setBackground(new java.awt.Color(255, 204, 51));
        btnIngSupplier.setForeground(new java.awt.Color(255, 0, 153));
        btnIngSupplier.setBorder(null);
        btnIngSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngSupplierActionPerformed(evt);
            }
        });
        add(btnIngSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 130));

        imgManufacturer.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgManufacturer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgManufacturer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Factory.png"))); // NOI18N
        add(imgManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 80, 60));

        lblManufacturer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        lblManufacturer.setText("Manufacturer");
        add(lblManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        btnManufacturer.setBackground(new java.awt.Color(0, 51, 153));
        btnManufacturer.setForeground(new java.awt.Color(255, 0, 153));
        btnManufacturer.setBorder(null);
        btnManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturerActionPerformed(evt);
            }
        });
        add(btnManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 120, 130));

        imgFDA.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgFDA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Licence.png"))); // NOI18N
        add(imgFDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 80, 60));

        lblANSI.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblANSI.setForeground(new java.awt.Color(255, 255, 255));
        lblANSI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblANSI.setText("ANSI");
        add(lblANSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 120, -1));

        btnANSI.setBackground(new java.awt.Color(0, 153, 51));
        btnANSI.setForeground(new java.awt.Color(255, 0, 153));
        btnANSI.setBorder(null);
        btnANSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnANSIActionPerformed(evt);
            }
        });
        add(btnANSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 130));

        imgDistributor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgDistributor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDistributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Truck.png"))); // NOI18N
        add(imgDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 80, 60));

        lblDistributor.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDistributor.setForeground(new java.awt.Color(255, 255, 255));
        lblDistributor.setText("Distributor");
        add(lblDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        btnDistributor.setBackground(new java.awt.Color(255, 153, 0));
        btnDistributor.setForeground(new java.awt.Color(255, 0, 153));
        btnDistributor.setBorder(null);
        btnDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributorActionPerformed(evt);
            }
        });
        add(btnDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 120, 130));

        imgMaterialDepot.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgMaterialDepot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMaterialDepot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Pharmacy Shop.png"))); // NOI18N
        add(imgMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 80, 60));

        lblMaterialDepot.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblMaterialDepot.setForeground(new java.awt.Color(255, 255, 255));
        lblMaterialDepot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaterialDepot.setText("Material Depot");
        add(lblMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 120, -1));

        btnMaterialDepot.setBackground(new java.awt.Color(255, 102, 153));
        btnMaterialDepot.setForeground(new java.awt.Color(255, 0, 153));
        btnMaterialDepot.setBorder(null);
        btnMaterialDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialDepotActionPerformed(evt);
            }
        });
        add(btnMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 120, 130));

        imgContractor.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        imgContractor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgContractor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Hospital 3.png"))); // NOI18N
        add(imgContractor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 80, 60));

        lblContractor.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblContractor.setForeground(new java.awt.Color(255, 255, 255));
        lblContractor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContractor.setText("Contractor");
        add(lblContractor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 120, -1));

        btnContractor.setBackground(new java.awt.Color(153, 204, 255));
        btnContractor.setForeground(new java.awt.Color(255, 0, 153));
        btnContractor.setBorder(null);
        btnContractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContractorActionPerformed(evt);
            }
        });
        add(btnContractor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 120, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnIngSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngSupplierActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(new IngredientSupplierFormJPanel(splitPane));
    }//GEN-LAST:event_btnIngSupplierActionPerformed

    private void btnManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturerActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(new ManufacturerFormJPanel(splitPane));
    }//GEN-LAST:event_btnManufacturerActionPerformed

    private void btnANSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnANSIActionPerformed
        // TODO add your handling code here:
       splitPane.setRightComponent(new ANSIFormJPanel(splitPane)); 
    }//GEN-LAST:event_btnANSIActionPerformed

    private void btnDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributorActionPerformed
        // TODO add your handling code here:
       splitPane.setRightComponent(new DistributorFormJPanel(splitPane));
    }//GEN-LAST:event_btnDistributorActionPerformed

    private void btnMaterialDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialDepotActionPerformed
        // TODO add your handling code here:
       splitPane.setRightComponent(new MaterialDepotFormJPanel(splitPane));
    }//GEN-LAST:event_btnMaterialDepotActionPerformed

    private void btnContractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContractorActionPerformed
        // TODO add your handling code here:
       splitPane.setRightComponent(new ContractorFormJPanel(splitPane));
    }//GEN-LAST:event_btnContractorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnANSI;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContractor;
    private javax.swing.JButton btnDistributor;
    private javax.swing.JButton btnIngSupplier;
    private javax.swing.JButton btnManufacturer;
    private javax.swing.JButton btnMaterialDepot;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel imgDistributor;
    private javax.swing.JLabel imgFDA;
    private javax.swing.JLabel imgContractor;
    private javax.swing.JLabel imgManufacturer;
    private javax.swing.JLabel imgMaterialDepot;
    private javax.swing.JLabel imgfactory;
    private javax.swing.JLabel imgingsupplier;
    private javax.swing.JLabel lblANSI;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblContractor;
    private javax.swing.JLabel lblDistributor;
    private javax.swing.JLabel lblIngredient;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblMaterialDepot;
    private javax.swing.JLabel lblRoleHeading;
    private javax.swing.JLabel lblSupplier;
    // End of variables declaration//GEN-END:variables
}
