/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.materialDepot;

import classes.Material;
import classes.MaterialDepot;
import classes.MaterialDepotOrderBook;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import util.sql.MaterialSqlQuery;
import util.sql.MaterialDepot_OrderBook_SqlQuery;

/**
 *
 * @author Dell
 */
public class MaterialDepotJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaterialDepotJPanel
     */
    DefaultPieDataset manANSItaset;
    DefaultPieDataset categoryDataset;
    MaterialDepot materialDepot;
    public MaterialDepotJPanel(MaterialDepot materialDepot) {
        initComponents();
        populateTable();
        populateOrdersTable();
        this.materialDepot = materialDepot;
        this.manANSItaset = new DefaultPieDataset();
        this.categoryDataset = new DefaultPieDataset();
        ArrayList<Material> mList = new ArrayList<>();
        MaterialSqlQuery msq = new MaterialSqlQuery();
        mList = msq.readAllMaterial();
        HashMap<String, Integer> manufacturerMap = new HashMap<>();
        HashMap<String, Integer> categoryMap = new HashMap<>();

        for (Material m : mList) {
            if(!m.getMaterial_Status().equals("Rejected")){
                if (manufacturerMap.containsKey(m.getManufacturer_Name())) {
                    int old = manufacturerMap.get(m.getManufacturer_Name());
                    manufacturerMap.put(m.getManufacturer_Name(), old + 1);
                } else {
                    manufacturerMap.put(m.getManufacturer_Name(), 1);
                }
                if (categoryMap.containsKey(m.getMaterial_Category())) {
                    int old = categoryMap.get(m.getMaterial_Category());
                    categoryMap.put(m.getMaterial_Category(), old + 1);
                } else {
                    categoryMap.put(m.getMaterial_Category(), 1);
                }
            }
        }

        manufacturerMap.forEach((k, v) -> this.manANSItaset.setValue(k, v));
        categoryMap.forEach((k, v) -> this.categoryDataset.setValue(k, v));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelInventoryM = new javax.swing.JTabbedPane();
        Inventory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnNewOrder = new javax.swing.JButton();
        btnViewManufacturer = new javax.swing.JButton();
        btnViewCategory = new javax.swing.JButton();
        lbllogo2 = new javax.swing.JLabel();
        MaterialDepot_Orders = new javax.swing.JPanel();
        lbllogo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMaterialDepotOrder = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Material Depot");

        PanelInventoryM.setBackground(new java.awt.Color(255, 255, 255));
        PanelInventoryM.setForeground(new java.awt.Color(0, 51, 153));
        PanelInventoryM.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.setForeground(new java.awt.Color(0, 51, 153));
        Inventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Material Name", "Material Category", "Date of Manufacturing", "Manufacturer Name", "Material Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMaterial);

        Inventory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 764, 530));

        btnNewOrder.setBackground(new java.awt.Color(0, 153, 255));
        btnNewOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnNewOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Eye.png"))); // NOI18N
        btnNewOrder.setText("VIEW");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });
        Inventory.add(btnNewOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 120, 34));

        btnViewManufacturer.setBackground(new java.awt.Color(255, 102, 102));
        btnViewManufacturer.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        btnViewManufacturer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Chart.png"))); // NOI18N
        btnViewManufacturer.setText("CHART1");
        btnViewManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewManufacturerActionPerformed(evt);
            }
        });
        Inventory.add(btnViewManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 120, 34));

        btnViewCategory.setBackground(new java.awt.Color(255, 153, 0));
        btnViewCategory.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Chart.png"))); // NOI18N
        btnViewCategory.setText("CHART2");
        btnViewCategory.setToolTipText("");
        btnViewCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCategoryActionPerformed(evt);
            }
        });
        Inventory.add(btnViewCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 120, 34));

        lbllogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        Inventory.add(lbllogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        PanelInventoryM.addTab("Central Inventory", Inventory);

        MaterialDepot_Orders.setBackground(new java.awt.Color(255, 255, 255));
        MaterialDepot_Orders.setForeground(new java.awt.Color(255, 255, 255));
        MaterialDepot_Orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        MaterialDepot_Orders.add(lbllogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 608, 110, 70));

        tblMaterialDepotOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material Name", "Material Category", "Manufacturer Name", "Material Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMaterialDepotOrder);

        MaterialDepot_Orders.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, 764, 530));

        PanelInventoryM.addTab("Material Depot Inventory Orders", MaterialDepot_Orders);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(PanelInventoryM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMaterial.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }

        ArrayList<Material> mList = new ArrayList<>();
        MaterialSqlQuery msq = new MaterialSqlQuery();
        mList = msq.readAllMaterial();
        String materialName = (String) tblMaterial.getValueAt(selectedRow, 0);
        Material m = mList.stream()
                .filter(material -> material.getMaterial_Name().equals(materialName))
                .findFirst()
                .orElse(null);
        if(m != null){
           new MaterialDepotJDialog(null, true, m, materialDepot).show();
            populateTable();
            populateOrdersTable(); 
        } 
        
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnViewManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewManufacturerActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createPieChart("Manufacturers", this.manANSItaset, true, true, false);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 450);
    }//GEN-LAST:event_btnViewManufacturerActionPerformed

    private void btnViewCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCategoryActionPerformed
        // TODO add your handling code here:
        JFreeChart chart = ChartFactory.createPieChart("Categories", this.categoryDataset, true, true, false);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(450, 450);
    }//GEN-LAST:event_btnViewCategoryActionPerformed
private void populateTable() {
        ArrayList<Material> mList = new ArrayList<>();
        MaterialSqlQuery msq = new MaterialSqlQuery();
        mList = msq.readAllMaterial();

        DefaultTableModel model = (DefaultTableModel) tblMaterial.getModel();
        model.setRowCount(0);

        for (Material e : mList) {
            Object row[] = new Object[10];
            row[0] = e.getMaterial_Name();
            row[1] = e.getMaterial_Category();
            row[2] = e.getDate_Of_Manufacture();
            row[3] = e.getManufacturer_Name();
            row[4] = e.getMaterial_Status();

            if ((e.getMaterial_Status().equals("Available"))) {
                model.addRow(row);
            }

        }
    }
  private void populateOrdersTable() {
        ArrayList<MaterialDepotOrderBook> hobList = new ArrayList<>();
        MaterialDepot_OrderBook_SqlQuery hsq = new MaterialDepot_OrderBook_SqlQuery();
        hobList = hsq.readAllMaterialDepotOrderBook();

        ArrayList<Material> mList = new ArrayList<>();
        MaterialSqlQuery msq = new MaterialSqlQuery();
        mList = msq.readAllMaterial();

        DefaultTableModel model = (DefaultTableModel) tblMaterialDepotOrder.getModel();
        model.setRowCount(0);

        for (MaterialDepotOrderBook e : hobList) {
            Object row[] = new Object[10];
            Material m = searchById(e.getMaterial_Id());
            row[0] = m.getMaterial_Name();
            row[1] = m.getMaterial_Category();
            row[2] = m.getManufacturer_Name();
            row[3] = e.getStatus();

            if ((e.getStatus().equals("Ordered"))) {
                model.addRow(row);
            }

        }
    }
   private Material searchById(int id) {
        Material m = null;
        ArrayList<Material> mList = new ArrayList<>();
        MaterialSqlQuery msq = new MaterialSqlQuery();
        mList = msq.readAllMaterial();
        for (Material e : mList) {
            if (e.getId() == id) {
                m = e;
            }
        }
        return m;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inventory;
    private javax.swing.JPanel MaterialDepot_Orders;
    private javax.swing.JTabbedPane PanelInventoryM;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnViewCategory;
    private javax.swing.JButton btnViewManufacturer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbllogo1;
    private javax.swing.JLabel lbllogo2;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTable tblMaterialDepotOrder;
    // End of variables declaration//GEN-END:variables
}
