/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model.communityadmin;

import classes.MaterialDepot;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.registration.MaterialDepotFormJPanel;
import util.sql.MaterialDepotSqlQuery;

/**
 *
 * @author Dell
 */
public class ViewMaterialDepotJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMaterialDepotJPanel
     */
    javax.swing.JSplitPane splitPane;
    public ViewMaterialDepotJPanel(javax.swing.JSplitPane splitPane) {
        initComponents();
        this.splitPane=splitPane;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterialDepot = new javax.swing.JTable();
        lblMaterialDepot = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnMaterialDepot = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        lbllogo = new javax.swing.JLabel();
        lblIVMaterialDepot = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMaterialDepot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Material Depot Name", "Location", "Inventory Size", "Email Id", "Password", "Phone  Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMaterialDepot);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 760, 520));

        lblMaterialDepot.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblMaterialDepot.setForeground(new java.awt.Color(153, 153, 153));
        lblMaterialDepot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaterialDepot.setText("VIEW MATERIAL DEPOT ");
        add(lblMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 420, 60));

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Remove.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 110, 30));

        btnMaterialDepot.setBackground(new java.awt.Color(0, 153, 255));
        btnMaterialDepot.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnMaterialDepot.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterialDepot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Eye.png"))); // NOI18N
        btnMaterialDepot.setText("VIEW");
        btnMaterialDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMaterialDepotActionPerformed(evt);
            }
        });
        add(btnMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 110, 30));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, -1, 90));
        add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 190, 0));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/AVSlogo.png"))); // NOI18N
        add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, 110, 70));

        lblIVMaterialDepot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIVMaterialDepot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/PLogo.jpg"))); // NOI18N
        add(lblIVMaterialDepot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 310, 180));

        btnCreate.setBackground(new java.awt.Color(0, 153, 51));
        btnCreate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/images/Plus(3).png"))); // NOI18N
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMaterialDepot.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }
        ArrayList<MaterialDepot> mList =  new  ArrayList<>();
        MaterialDepotSqlQuery msq = new MaterialDepotSqlQuery();
        mList = msq.readAllMaterialDepot();
        MaterialDepot p = mList.get(selectedRow);
        
        msq.deleteMaterialDepot(p);
        
        
        
        populateTable();

        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewMaterialDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMaterialDepotActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMaterialDepot.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit");
            return;
        }
         ArrayList<MaterialDepot> mList =  new  ArrayList<>();
        MaterialDepotSqlQuery msq = new MaterialDepotSqlQuery();
        mList = msq.readAllMaterialDepot();
        MaterialDepot p = mList.get(selectedRow);
        
        splitPane.setRightComponent(new UpdateMaterialDepotFormJPanel(splitPane,p));
         populateTable();
    }//GEN-LAST:event_btnViewMaterialDepotActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        splitPane.setRightComponent(new MaterialDepotFormJPanel(splitPane));
        populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

        private void populateTable() {
        ArrayList<MaterialDepot> mList =  new  ArrayList<>();
        MaterialDepotSqlQuery msq = new MaterialDepotSqlQuery();
        mList = msq.readAllMaterialDepot();
        
        
        DefaultTableModel model =(DefaultTableModel) tblMaterialDepot.getModel();
        model.setRowCount(0);
        
        for(MaterialDepot e: mList){
            System.out.println(e);
            Object row[]=new Object[10];
            row[0] = e.getMaterialDepot_Name();
            row[1] = e.getMaterialDepot_Location();
            row[2] = e.getMaterialDepot_Inventory_Size();
            row[3] = e.getEmail_Id();
            row[4] = e.getPassword();
            row[5] = e.getPhone_No();
            
            model.addRow(row);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMaterialDepot;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIVMaterialDepot;
    private javax.swing.JLabel lblMaterialDepot;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTable tblMaterialDepot;
    // End of variables declaration//GEN-END:variables
}
